---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: app-sre-vault
  namespace: app-sre-tenant
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: "https://vault.ci.ext.devshift.net"
      # Path is the mount path of the Vault KV backend endpoint
      # Used as a path prefix for the external secret key
      path: app-sre-v2
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: v2
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: approle
          # RoleID configured in the App Role authentication backend
          roleId: "" # will be added by the overlay
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: secret-store-credentials
            key: secret-id
            namespace: app-sre-tenant

